### ISSUE TITLE
Doesn't work with M2 CE

### ISSUE THREAD

**Issue by n0kit31** [richdynamix/personalised-products#27]
Extension calls classes that are not available in Community Edition. Only in Enterprise Edition. Di:compile cannot be successfully finished though.
Furthermore, these classes are not used later.

**Comment by richdynamix** [comment]
Which version of M2 are you using? This extension was developed on 2.0.0 and has not been updated for anything newer.

**Comment by n0kit31** [comment]
I'm using 2.2.2
Version 2.0.0 is useless nowadays.

**Comment by richdynamix** [comment]
It is indeed. As I said, it was never updated past the initial release. There has been no code updates in over 2 years. I would assume a lot of changes will be required.

**Comment by n0kit31** [comment]
Will fork it. Thanks for reply!
